#!/usr/bin/env python

import sys
sys.path.append('/usr/share/endless-os-photos')
from src.endless_photos import EndlessPhotos
from gi.repository import GtkClutter, GLib, Gdk

app = EndlessPhotos()
app.run(sys.argv)
