#!/usr/bin/env python

import sys
sys.path.append('/usr/share/endless-os-photos')
from src import EndlessPhotos
from gi.repository import GtkClutter, GLib, Gdk

app = EndlessPhotos()
GLib.threads_init()
Gdk.threads_init()
GtkClutter.init([])
app.run(sys.argv)
