#!/usr/bin/env python

import sys
sys.path.append('/usr/share/endless-os-photos')
from src import EndlessPhotos
from gi.repository import GtkClutter, GObject


GObject.threads_init()
GtkClutter.init([])
app = EndlessPhotos()
app.run(sys.argv)
